uploads = []
generated = []

[[outputs]]
id = "GTQ3n85P4cdCbGqbMRnaY"
uri = "file://reporting-library.tar.gz"
type = "unspecified"
title = "Reporting Library (dao-sdk + ReportingModule)"

[[outputs]]
id = "iw2IRPI1UCyUKRyhOtfxY"
uri = "file://report_dao-sdk.tar.gz"
type = "unspecified"
title = "report_dao-sdk (merged single module)"
